const fs = require('fs');
const path = require('path');

const count = parseInt(process.argv[2]) || 5;
const targetPath = path.join(__dirname, '../Skins/Tautulli/@Resources/meters.inc');

console.log(`Generating ${count} meters...`);

let output = `; ------------------------------------------------------------------------
; GENERATED METERS - DO NOT EDIT MANUALLY
; Generated by gen_meters.js
; ------------------------------------------------------------------------

[Variables]
MaxRows=${count}

`;

for (let i = 1; i <= count; i++) {
    const isFirst = i === 1;
    const yValue = isFirst ? '50' : '10R';

    output += `; --- Row ${i} ---
[MeterGroup${i}]
Group=StreamRow | Row${i}
Hidden=1

[User${i}Name]
Meter=String
MeterStyle=StyleTextName
Group=StreamRow | Row${i}
Y=${yValue}

[User${i}Details]
Meter=String
MeterStyle=StyleTextDetail
Group=StreamRow | Row${i}

[User${i}BarBack]
Meter=Image
MeterStyle=StyleBarBack
Group=StreamRow | Row${i}

[User${i}Bar]
Meter=Image
MeterStyle=StyleBarFront
Group=StreamRow | Row${i}

[User${i}Hitbox]
Meter=Image
MeterStyle=StyleHitbox
Group=StreamRow | Row${i}

`;
}

// Ensure dir exists
const dir = path.dirname(targetPath);
if (!fs.existsSync(dir)) {
    console.log(`Creating directory ${dir}...`);
    fs.mkdirSync(dir, { recursive: true });
}

fs.writeFileSync(targetPath, output, { encoding: 'utf16le' });
console.log(`Successfully generated ${count} meters to ${targetPath}`);
